"""Application-wide constants for the trading bot."""

APP_NAME: str = "ml-trading-bot"
APP_VERSION: str = "0.1.0"
MAX_OPEN_POSITIONS: int = 5
STOCK_SHORT_BALANCE_THRESHOLD: float = 2_500.0
CANDLE_FETCH_DELAY_SECONDS: int = 17
CANDLE_LOCK_TTL_SECONDS: int = 7_200
CANDLE_HEARTBEAT_TTL_SECONDS: int = 3_600
DEFAULT_CANDLE_SOURCE: str = "tradier"
DEFAULT_RESEARCH_SOURCE: str = "alpaca_training"
ALPACA_BATCH_MAX_SYMBOLS: int = 200
ALPACA_SYNC_LOOKBACK_DAYS: int = 730
ALPACA_DEFAULT_TIMEFRAME: str = "1Day"
ALPACA_DEFAULT_SOURCE: str = "alpaca_training"
NEWS_MIN_CONFIDENCE: float = 0.65
MIN_INSIDER_PURCHASE_VALUE: float = 50_000.0
MAX_WATCHLIST_SIZE: int = 20
WATCHLIST_PROMOTION_THRESHOLD: float = 65.0
WATCHLIST_AUTO_ADD_THRESHOLD: float = 80.0
WATCHLIST_DEMOTION_THRESHOLD: float = 30.0
WATCHLIST_DEMOTION_DAYS: int = 5
CONGRESS_PROMOTION_THRESHOLD: float = 70.0
INSIDER_PROMOTION_THRESHOLD: float = 0.75
MAX_SINGLE_POSITION_PCT: float = 0.20
MAX_TOTAL_CAPITAL_AT_RISK_PCT: float = 0.06
DAILY_LOSS_LIMIT_PCT: float = 0.02
WEEKLY_DRAWDOWN_LIMIT_PCT: float = 0.05
PEAK_DRAWDOWN_LIMIT_PCT: float = 0.15
LIQUIDITY_POSITION_PCT: float = 0.01
DEFAULT_MAX_STOCK_POSITIONS: int = 3
DEFAULT_MAX_CRYPTO_POSITIONS: int = 3
RESEARCH_SCORE_BONUS_THRESHOLD_1: float = 70.0
RESEARCH_SCORE_BONUS_THRESHOLD_2: float = 85.0
RESEARCH_SCORE_BONUS_1: float = 1.15
RESEARCH_SCORE_BONUS_2: float = 1.25
DEFAULT_SIGNAL_WEIGHTS: dict[str, float] = {
    "news_sentiment_7d": 0.20,
    "congress_buy": 0.30,
    "insider_buy": 0.25,
    "screener_pass": 0.15,
    "analyst_upgrade": 0.10,
}
